export const FUSE_TYPE = [
    { viewValue: '汽油#89', value: 'PETROL89' },
    { viewValue: '汽油#92', value: 'PETROL92' },
    { viewValue: '汽油#95', value: 'PETROL95' },
    { viewValue: '柴油#0', value: 'DIESEL0' },
    { viewValue: '柴油#5', value: 'DIESEL5' },
    { viewValue: '柴油#10', value: 'DIESEL10' },
    { viewValue: '柴油#20', value: 'DIESEL20' },
    { viewValue: '柴油#35', value: 'DIESEL35' },
    { viewValue: '柴油#50', value: 'DIESEL50' }
];

export const VEHICLE_TYPE = [
    { viewValue: '微型汽车', value: 'MICRO' },
    { viewValue: '紧凑汽车', value: 'COMPACT' },
    { viewValue: '小型汽车', value: 'SMALL' },
    { viewValue: '中性汽车', value: 'MEDIUM' },
    { viewValue: '中大型汽车', value: 'MIDPLUS' },
    { viewValue: '面包车', value: 'VAN' },
    { viewValue: '大型汽车', value: 'LARGE' },
    { viewValue: '小型SUV', value: 'SMALL_SUV' },
    { viewValue: '中大型SUV', value: 'MIDPLUS_SUV' },
    { viewValue: '多人乘坐用MPV', value: 'MPV' },
    { viewValue: '运动汽车', value: 'SPORTCAR' },
    { viewValue: '皮卡车', value: 'PICKUP' },
];
export const VEHICLE_BRAND = [
    // 日系
    { value: '丰田', viewValue: '丰田' },
    { value: '雷克萨斯', viewValue: '雷克萨斯' },
    { value: '本田', viewValue: '本田' },
    { value: '讴歌', viewValue: '讴歌' },
    { value: '马自达', viewValue: '马自达' },
    { value: '日产', viewValue: '日产' },
    { value: '英菲尼迪', viewValue: '英菲尼迪' },
    { value: '斯巴鲁', viewValue: '斯巴鲁' },
    { value: '三菱', viewValue: '三菱' },
    { value: '现代', viewValue: '现代' },
    { value: '起亚', viewValue: '起亚' },
    // 美系
    { value: '福特', viewValue: '福特' },
    { value: '雪佛兰', viewValue: '雪佛兰' },
    { value: '凯迪拉克', viewValue: '凯迪拉克' },
    { value: '林肯', viewValue: '林肯' },
    { value: '别克', viewValue: '别克' },
    { value: 'Jeep', viewValue: 'Jeep' },
    { value: '特斯拉', viewValue: '特斯拉' },
    // 欧洲 德系
    { value: '沃尔沃', viewValue: '沃尔沃' },
    { value: '宝马', viewValue: '宝马' },
    { value: '奔驰', viewValue: '奔驰' },
    { value: '奥迪', viewValue: '奥迪' },
    { value: '大众', viewValue: '大众' },
    { value: '宝沃', viewValue: '宝沃' },
    { value: '保时捷', viewValue: '保时捷' },
    { value: '路虎', viewValue: '路虎' },
    { value: '宾利', viewValue: '宾利' },
    { value: '捷豹', viewValue: '捷豹' },
    { value: '标致', viewValue: '标致' },
    { value: '雪铁龙', viewValue: '雪铁龙' },
    // 国产
    { value: '广汽传祺', viewValue: '广汽传祺' },
    { value: '吉利', viewValue: '吉利' },
    { value: '五菱', viewValue: '五菱' },
    { value: '宝骏', viewValue: '宝骏' },
    { value: '海马', viewValue: '海马' },
    { value: '一汽', viewValue: '一汽' },
    { value: '东风', viewValue: '东风' },
    { value: '奇瑞', viewValue: '奇瑞' },
    { value: '长安', viewValue: '长安' },
    { value: '红旗', viewValue: '红旗' },
    { value: '江铃', viewValue: '江铃' },
];
export const provinceAbbr = [
    { value: '粤', viewValue: '粤' },
    { value: '赣', viewValue: '赣' },
    { value: '湘', viewValue: '湘' },
    { value: '京', viewValue: '京' },
    { value: '冀', viewValue: '冀' },
    { value: '苏', viewValue: '苏' },
    { value: '豫', viewValue: '豫' },
    { value: '辽', viewValue: '辽' },
    { value: '黑', viewValue: '黑' },
    { value: '皖', viewValue: '皖' },
    { value: '新', viewValue: '新' },
    { value: '鄂', viewValue: '鄂' },
    { value: '晋', viewValue: '晋' },
    { value: '陕', viewValue: '陕' },
    { value: '吉', viewValue: '吉' },
    { value: '青', viewValue: '青' },
    { value: '甘', viewValue: '甘' },
    { value: '贵', viewValue: '贵' },
    { value: '浙', viewValue: '浙' },
    { value: '鲁', viewValue: '鲁' },
    { value: '蒙', viewValue: '蒙' },
    { value: '藏', viewValue: '藏' },
    { value: '闽', viewValue: '闽' },
    { value: '川', viewValue: '川' },
    { value: '琼', viewValue: '琼' },
    { value: '云', viewValue: '云' }
];
